repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        stages: [commit]
        language: system
        entry: docker-compose run web isort
        types: [python]

      - id: black
        name: black
        stages: [commit]
        language: system
        entry: docker-compose run web black
        types: [python]

      - id: flake8
        name: flake8
        stages: [commit]
        language: system
        entry: docker-compose run web flake8
        types: [python]
        exclude: setup.py

      - id: mypy
        name: mypy
        stages: [commit]
        language: system
        entry: docker-compose run web mypy
        types: [python]
        pass_filenames: false

      - id: pytest
        name: pytest
        stages: [commit]
        language: system
        entry: docker-compose run web pytest
        pass_filenames: false
        types: [python]

      - id: pytest-cov
        name: pytest
        stages: [ push ]
        language: system
        entry: docker-compose run web pytest --cov --cov-fail-under=95
        types: [ python ]
        pass_filenames: false
