version: "3.7"

services:
  web:
    build:
      context: .
      target: python-base
    image: poc-fastapi
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    command: "--development"
    depends_on:
      - db
    ports:
      - 8000:8000

  db:
    image: postgres:13.2-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file: .env
    ports:
      - 5432:5432

volumes:
  db-data: